import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import logo from '../public/logo.png'
import Link from 'next/link'
import Hero from '../components/Hero'
import Choice from '../components/Choice'
import About from '../components/About'
import Ro_common from "../JSON/RO-common.json"
import Ro_routes from "../JSON/RO-routes.json"

export const getServerSideProps = () => {
  let citydata = Ro_common

  return {
      props: { cityData : citydata }
  }
}


export default function Home({cityData}) {
  console.log("cityData is working")
  return (
    <div className={styles.container}>
      <Head>
        <title>Urban Service</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero></Hero>
      <Choice></Choice>
      <About></About>

    </div>
  )
}
